version: "3.3"
services:
  scraper-service:
    build:
      context: ./scraper
      dockerfile: ./Dockerfile
    ports:
      - 3002:3002
    networks:
      - mlnet

  ml-service:
    build:
      context: ./ml
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - scrapernet

  bing-chat-service:
    build:
      context: ./bing-chat
      dockerfile: ./Dockerfile
    ports:
      - 3003:3003
    networks:
      - bingchatnet

  backend-service:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - mongonet
      - scrapernet
      - mlnet
      - bingchatnet
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mongo
      - scraper-service
      - ml-service
      - bing-chat-service

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/mealo
    networks:
      - mongonet

networks:
  mongonet:
  scrapernet:
  bingchatnet:
  mlnet:

volumes:
  mongodata:
