version: "3.3"
services:
  scraper-service:
    build:
      context: ./scraper
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - scrapernet

  backend-service:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - mongonet
      - scrapernet
    depends_on:
      - mongo
      - scraper-service

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/mealo
    networks:
      - mongonet

networks:
  mongonet:
  scrapernet:

volumes:
  mongodata:
