export const recipeMock = {
  _id: '1',
  id: '1',
  uid: 'test',
  title: 'Mock Recipe',
  totalTime: '30 minutes',
  ingredients: ['Ingredient 1', 'Ingredient 2'],
  instructions: ['Step 1', 'Step 2'],
  image: 'mock-image.jpg',
  author: 'Mock Author',
  canonical_url: 'http://mock-url.com',
  category: 'Mock Category',
  cookTime: '20 minutes',
  cuisine: 'Mock Cuisine',
  description: 'Mock Description',
  host: 'Mock Host',
  language: 'English',
  nutrients: 'Mock Nutrients',
  prepTime: '10 minutes',
  ratings: '4.5',
  reviews: '10',
  siteName: 'Mock Site',
  yields: '4 servings',
  is_favorite: false,
  speed: 'Medium',
  calories: '200',
  difficulty: 'Easy',
  folders: ['Folder 1', 'Folder 2'],
  meals: [
    {
      id: '1',
      day: '2024-02-22T12:00:00Z',
      meal: 'Breakfast',
      recipe: '1',
    },
    {
      id: '2',
      day: '2024-02-22T12:00:00Z',
      meal: 'Lunch',
      recipe: '1',
    },
    {
      id: '3',
      day: '2024-02-22T12:00:00Z',
      meal: 'Dinner',
      recipe: '1',
    },
  ],
  video: 'http://mock-video.com',
};
